site_name: TossPayments Python Server SDK
site_description: Python SDK for TossPayments API - Simple and intuitive server-side payment processing
site_url: https://jhwang0801.github.io/tosspayments-python-server-sdk/
repo_url: https://github.com/jhwang0801/tosspayments-python-server-sdk
repo_name: jhwang0801/tosspayments-python-server-sdk

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [tosspayments_server_sdk]
          options:
            docstring_style: google
            show_source: false

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Quickstart: getting-started/quickstart.md
  - API Reference:
    - Client: api-reference/client.md
    - PaymentResource: api-reference/payments.md
    - WebhookResource: api-reference/webhooks.md
    - Models: api-reference/models.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details